### ISSUE TITLE
Parameters that should be nullable are non-nullable

### ISSUE THREAD

**Issue by leonluc-dev** [Softeq/Toast-xamarin-ios#9]
In the original Objective-C library of this binding several parameters (`title`, `image`, `style` and `completion`) are nullable as can be seen in this example:

``` 
 [self.navigationController.view makeToast:@"This is a piece of toast with a title"
                                         duration:2.0
                                         position:CSToastPositionTop
                                            title:nil
                                            image:nil
                                            style:nil
                                       completion:nil];
```

However, in the binding calling the following method results in  an ArgumentNullException:

`myView.MakeToast("Test text", 2.0f, CSToastPosition.Top, null, null, null, null);`

It seems these parameters haven't had their [[NullAllowed]](https://learn.microsoft.com/en-us/xamarin/cross-platform/macios/binding/binding-types-reference#NullAllowedAttribute) attributes set.

**Comment by wcoder** [comment]
@leonluc-dev Thank you for the feedback!

Please check the new NuGet package [v4.0.0.3](https://www.nuget.org/packages/ToastBindings/4.0.0.3)

**Comment by leonluc-dev** [comment]
Thanks. Nullability seems to work perfectly now!
